"""Reference implementation: Attention on the Spring 26 NPU.

Generated by autocomp (translated from numpy reference, 3,630 cycles).

Problem: compute unscaled dot-product attention for:
  Q: (64, 16) FP8   at QUERY_BASE
  K: (16, 16) FP8   at KEY_BASE
  V: (16, 16) FP8   at VALUE_BASE
  output: (64, 16) BF16 at OUTPUT_BASE

Algorithm:
  scores      = Q_pad @ K_pad          (matmul.mxu0; FP8 inputs, BF16 out)
  softmax_wts = softmax(scores, dim=-1) (vexp + vrot.reduce.sum + vrcp + vmul)
  output      = softmax_fp8 @ V_pad    (matmul.mxu0; softmax BF16 bytes reinterp as FP8)

Memory layout (must match tests/npu-kernels/test3.py):
  QUERY_BASE  = 0x0000  -- Q  (64×16 FP8,   1024 bytes)
  KEY_BASE    = 0x2000  -- K  (16×16 FP8,    256 bytes)
  VALUE_BASE  = 0x3000  -- V  (16×16 FP8,    256 bytes)
  OUTPUT_BASE = 0x4000  -- output (64×16 BF16, 2048 bytes)
"""
from typing import List, Tuple
import torch
from npu_model.software import Instruction, Program

QUERY_BASE  = 0x0000
KEY_BASE    = 0x2000
VALUE_BASE  = 0x3000
OUTPUT_BASE = 0x4000


class GeneratedProgram(Program):
    instructions: List[Instruction] = [
        # ── Load all inputs back-to-back so DMA transfers overlap ─────────────
        # Q: 1024 bytes FP8 (64×16) → mrf[0]
        # K: 256 bytes FP8 (16×16)  → wb_mxu0[0]
        # V: 256 bytes FP8 (16×16)  → wb_mxu0[1]
        Instruction("dma.load",      {"rd": 0, "base": QUERY_BASE,  "size": 1024, "flag": 0}),
        Instruction("dma.load.mxu0", {"rd": 0, "base": KEY_BASE,   "size": 256,  "flag": 1}),
        Instruction("dma.load.mxu0", {"rd": 1, "base": VALUE_BASE, "size": 256,  "flag": 2}),

        # ── Wait for Q and K before first matmul ─────────────────────────────
        Instruction("dma.wait",      {"flag": 0}),
        Instruction("dma.wait",      {"flag": 1}),

        # ── Matmul 1: scores = Q_pad @ K_pad  (MXU0) ─────────────────────────
        # mrf[0] read as (64,32) FP8; wb_mxu0[0] as (32,16) FP8
        # mrf[1] (zeroed) += Q_pad @ K_pad  →  (64,16) BF16
        Instruction("matmul.mxu0",   {"rd": 1, "rs1": 0, "rs2": 0}),
        Instruction("delay",         {"imm": 63}),  # matmul latency ~64 cycles

        # ── Softmax (VPU, all BF16) ───────────────────────────────────────────
        Instruction("vexp",            {"vrd": 2, "vs1": 1}),          # exp(scores)
        Instruction("delay",           {"imm": 7}),                     # VPU latency ~8 cycles
        Instruction("vrot.reduce.sum", {"vrd": 3, "vs1": 2}),          # row-wise sum, broadcast
        Instruction("delay",           {"imm": 7}),
        Instruction("vrcp",            {"vrd": 4, "vs1": 3}),          # 1 / row_sum
        Instruction("delay",           {"imm": 7}),
        Instruction("vmul",            {"vrd": 5, "vs1": 2, "vs2": 4}),# exp * rcp = softmax
        Instruction("delay",           {"imm": 7}),

        # ── Wait for V (almost certainly done by now) ─────────────────────────
        Instruction("dma.wait",      {"flag": 2}),

        # ── Matmul 2: output = softmax_fp8 @ V_pad  (MXU0) ───────────────────
        # mrf[5] BF16 bytes reinterpreted as (64,32) FP8 by MXU0
        # wb_mxu0[1] as (32,16) FP8
        # mrf[6] (zeroed) += softmax_fp8 @ V_pad  →  (64,16) BF16
        Instruction("matmul.mxu0",   {"rd": 6, "rs1": 5, "rs2": 1}),

        # Issue store immediately (async); dma.wait serialises on both
        # matmul2 completion and DMA transfer, hiding the ~64-cycle tail.
        Instruction("dma.store",     {"rs1": 6, "base": OUTPUT_BASE, "size": 2048, "flag": 3}),
        Instruction("dma.wait",      {"flag": 3}),
    ]

    memory_regions: List[Tuple[int, torch.Tensor]] = []


# ── Standalone test ───────────────────────────────────────────────────────────
import os
import sys
import tempfile

SEQ_LEN  = 64
HEAD_DIM = 16

QUERY_DATA = torch.ones((SEQ_LEN, HEAD_DIM), dtype=torch.float8_e4m3fn)
KEY_DATA   = torch.ones((HEAD_DIM, HEAD_DIM), dtype=torch.float8_e4m3fn)
VALUE_DATA = torch.ones((HEAD_DIM, HEAD_DIM), dtype=torch.float8_e4m3fn)


def get_memory_regions():
    return [
        (QUERY_BASE,  QUERY_DATA),
        (KEY_BASE,    KEY_DATA),
        (VALUE_BASE,  VALUE_DATA),
    ]


def get_golden_result():
    Q_pad = torch.zeros(SEQ_LEN, 32, dtype=torch.float8_e4m3fn)
    Q_pad[:, :HEAD_DIM] = QUERY_DATA
    K_pad = torch.zeros(32, HEAD_DIM, dtype=torch.float8_e4m3fn)
    K_pad[:HEAD_DIM, :] = KEY_DATA
    V_pad = torch.zeros(32, HEAD_DIM, dtype=torch.float8_e4m3fn)
    V_pad[:HEAD_DIM, :] = VALUE_DATA

    scores  = (Q_pad.float() @ K_pad.float()).to(torch.bfloat16)
    exp_s   = torch.exp(scores.float()).to(torch.bfloat16)
    row_sum = exp_s.float().sum(dim=-1, keepdim=True).expand_as(exp_s).to(torch.bfloat16)
    softmax = (exp_s.float() / row_sum.float()).to(torch.bfloat16)
    softmax_fp8 = softmax.contiguous().view(torch.uint8).view(torch.float8_e4m3fn).reshape(SEQ_LEN, 32)
    expected = (softmax_fp8.float() @ V_pad.float()).to(torch.bfloat16)
    return (OUTPUT_BASE, expected)


def run_and_check(program_cls=GeneratedProgram) -> bool:
    import npu_model.configs.isa_definition
    from npu_model.simulation import Simulation
    from npu_model.logging import LoggerConfig
    from npu_model.configs.hardware.default import DefaultHardwareConfig

    program = program_cls()
    program.memory_regions = get_memory_regions()

    with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
        trace_path = f.name
    try:
        sim = Simulation(
            hardware_config=DefaultHardwareConfig(),
            logger_config=LoggerConfig(filename=trace_path),
            program=program,
            verbose=False,
        )
        sim.run(max_cycles=200_000)
        cycles = sim.get_stats()["cycles"]
    finally:
        try:
            os.unlink(trace_path)
        except OSError:
            pass

    if cycles >= 200_000:
        print("FAIL: hit max_cycles limit")
        return False

    output_base, expected = get_golden_result()
    raw = sim.core.arch_state.read_memory(output_base, expected.numel() * expected.element_size())
    actual = raw.view(expected.dtype).reshape(expected.shape)

    if actual.isnan().any() or actual.isinf().any():
        print("FAIL: output contains NaN or Inf")
        return False

    if torch.allclose(actual.float(), expected.float(), atol=0.02):
        print(f"PASS  ({cycles} cycles)")
        return True

    max_diff = (actual.float() - expected.float()).abs().max().item()
    print(f"FAIL: max_diff={max_diff:.4f} (atol=0.02)")
    return False


if __name__ == "__main__":
    ok = run_and_check()
    sys.exit(0 if ok else 1)
